Add Loongarch Support.
loongarch64-archive/jemalloc pull request #4
Opened 2021-08-18 09:03 UTC by wangjl-uos

Add Loongarch Support.

Modify: include/jemalloc/internal/quantum.h.
This change statemen minimum allocation alignment is 2^LG_QUANTUM in Loongarch.

2021-09-01 09:15 UTC, wangjl-uos commented
@yetist : 老师，您好，请教一下，我这个可以合并吗。

2021-09-06 06:22 UTC, wangjl-uos commented
@yetist，请教一下，这个代码是有不对的地方吗？

2021-09-06 10:39 UTC, xen0n approved these changes, later dismissed
Looks very good!

2021-09-06 10:44 UTC, xen0n commented
啊，忘记看 commit message 了，比较啰嗦，抓不住重点，且中式英语。

鉴于你实际做的事情只是给 LoongArch（注意大小写）添加了 `LG_QUANTUM` 定义，你直接写一行 `Define LG_QUANTUM for LoongArch` 就好了。

另外，内容是对于所有 `__loongarch__` 都指定默认最小对齐是 16 字节，那么 32 位的场景应该是多少？如果也是 16 那可以保持这个写法，还可以加个注释 `/* Minimum allocation alignment is 16-byte on both LoongArch 32-bit and 64-bit. */` 更好看了。

2021-09-07 01:47 UTC, wangjl-uos commented
@xen0n 按照上述意见已经修改。

2021-09-07 02:06 UTC, yetist commented
32位不确定是否应该按2^4对齐

2021-09-07 02:26 UTC, wangjl-uos commented
@yetist 那是把这句中的32-bit 去掉吗：/* Minimum allocation alignment is 16-byte on both LoongArch 32-bit and 64-bit. */

2021-09-09 03:09 UTC, yetist commented
`dev` 分支是上游的主开发分支，而且已经比当前仓库新了，你的提交不应该直接在 `dev` 分支上进行，请新创建一个分支进行。

2021-09-09 05:34 UTC, xen0n requested changes

2021-09-09 05:34 UTC, xen0n commented on include/jemalloc/internal/quantum.h
> + * Minimum allocation alignment is 16-byte on both LoongArch 64-bit.
不讲究，修复一下英语语法

2021-09-09 05:48 UTC, xen0n commented on include/jemalloc/internal/quantum.h
> +#  ifdef __loongarch__
还是不对吧？前面写的只判断64位，这里怎么判断的是全部LA

2021-09-09 05:54 UTC, wangjl-uos commented on include/jemalloc/internal/quantum.h
> +#  ifdef __loongarch__
起初我写的是 LA，前面没有加 32-bit 还是 64-bit 的注释，然后说最好加上 32 bit 和 64 bit， 我加上了，最后又反馈，32-bit 不确定，所以去掉了，现在我是应该把 64-bit 也去掉吗，就可以了吧。

2021-09-09 05:58 UTC, xen0n commented on include/jemalloc/internal/quantum.h
> +#  ifdef __loongarch__
> 起初我写的是 LA，前面没有加 32-bit 还是 64-bit 的注释，然后说最好加上 32 bit 和 64 bit， 我加上了，最后又反馈，32-bit 不确定，所以去掉了，现在我是应该把 64-bit 也去掉吗，就可以了吧。
> 

显然不是这意思，你先搞明白一下你预期的语义是什么，然后确保代码和注释是一致的，代码不准确就改代码，注释不准确就改注释

2021-09-26 07:36 UTC, cnmushiba commented
这个不能这么close，不然就没有人review了。所有的修改，最后squash一下，然后强制推送就好了。

2021-09-26 09:26 UTC, closed without merging